### ISSUE TITLE
UNMAINTAINED-BlackCat_NeuralNetworks-Version-2-master how to use this project?

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/BlackCat_Tensors#16] opened 2019-07-15 09:05 UTC
I want use your UNMAINTAINED-BlackCat_NeuralNetworks-Version-2-master to predict load forecast, but you UNMAINTAINED-BlackCat_NeuralNetworks-Version-1 crash and train nall, but when i use your UNMAINTAINED-BlackCat_NeuralNetworks-Version-2-master ,don't know how to use!

**Comment by josephjaspers** [comment] 2019-07-15 14:36
Hi, I no longer work on 'UNMAINTAINED-BlackCat_NeuralNetworks-Version-1/2' anymore. I would recommend using the BlackCat_Tensors project and its Neural Network module to attempt to solve your problem. 

The newer version that I actively work on should be much faster for training. 

I just added some examples to showcase you how to use the newer version. I'm planning on adding "training methods" and other utility functions to make their usage easier in the future.

**Comment by xinsuinizhuan** [comment] 2019-07-16 00:39
thank you!let me hava a try! I only want to use lstm method, because it hava the long and short memery,so it works well for power load forecast!

**Comment by xinsuinizhuan** [comment] 2019-07-16 00:45
Could you add the method in BlackCat_NeuralNetworks-Version-2-master to BlackCat_Tensors project,like RNN、lstm and others, because i think the lstm is the  best methord for forecast at present!

**Comment by josephjaspers** [comment] 2019-07-16 14:59
Yes, I will add them when I have the chance. I added a makefile to the example as well.

**Comment by josephjaspers** [comment] 2019-07-23 21:01
Duplicate of :
https://github.com/josephjaspers/BlackCat_Tensors/issues/18

**Closed** 2019-07-23 21:05 UTC
